miguel changes
akamai/amp-docs-ios pull request #3
Opened 2024-08-06 21:39 UTC by mchacong

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes requested changes
Miguel please review the comments,

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes commented on modules/amp-360/pages/amp-360-plugin.adoc
> +The Amp 360 plugin allows you to play corretly content formatted for virtual reality purposes.
@mchacong  Miguel,

typo:
correctly

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes commented on modules/amp-360/pages/amp-360-plugin.adoc
> +* {amp-plugin-sample-ios}[AMP {plugin-common-name} application sample for iOS].
@mchacong  
Miguel,
what is the link, or indication for the user to find/download corresponding samples.?

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes commented on modules/amp-360/pages/amp-360-plugin.adoc
> +The first step is to use the 360 plugin is to import the plugin.
@mchacong 
Miguel, 
syntax issue
the first step for using the Amp-360 plugin is ...

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes commented on modules/amp-downloader/pages/amp-downloader-plugin.adoc
> +The first step is to use the Downloader is to import the plugin.
same syntax issue , here and others.. @mchacong 
Miguel

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes commented on modules/amp-downloader/pages/amp-downloader-plugin.adoc
> +        array = []
maybe this else is not required as array is already empty. 
just a note.

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes commented on modules/amp-downloader/pages/amp-downloader-plugin.adoc
> +`AmpDownloadManager.cancelDownload`: Deletes the download
is the cancel (stop while downloading the asset) the same method used for delete (remove already downloaded asset). ??

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes commented on modules/amp-firebase/pages/amp-firebase-plugin.adoc
> +The AmpFirebase plugin offers a quick and escalable way to integrate AmpPlayer with {amp-plugin-docs}[Google Firebase]. This plugin enables the reporting of data collected by AMP in your application
typo ipmortant

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes commented on modules/amp-firebase/pages/amp-firebase-plugin.adoc
> +Yo can override as many methods as you want and even add your own logic on how the information changes across time. There are ways to add additional arguments for every event, for a single category o
typo
Yo

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes commented on modules/amp-meta/pages/amp-facebook-plugin.adoc
> +The AmpFBAudienceNetwork plugin offers a quick way to integrate AmpPlayer with {amp-plugin-docs}[Mux SDK]. This plugin enables the display of ads in your playback.
Facebook or Mux?

2024-08-09 00:26 UTC, JeanCarlosChavarriaHughes commented on modules/amp-yospace/pages/amp-yospace-plugin.adoc
> += YoSpace Analytics
I am confused @mchacong @orlando-amp Miguel, I thought our yospace integration is just for SSAI Ads. 

I am not aware of Yospace Analytics, 
is this file correct?

2024-08-16 22:16 UTC, mchacong commented
push miguel changes

2024-08-19 14:22 UTC, JeanCarlosChavarriaHughes approved these changes

2024-10-17 15:30 UTC, merged